server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**
        - id: review-service
          uri: http://localhost:8081
          predicates:
            - Path=/reviews/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/carts/**